### ISSUE TITLE
Complaint about moderation actions

### ISSUE THREAD

**Issue by 2colours** [Raku/Raku-Steering-Council#57]
https://irclogs.raku.org/raku-dev/2024-01-10.html#16:39

I don't have high expectations but this is really too much: somebody issuing bans based on personal distaste WHILE making personal remarks. I'd hope at least the other members recognize that this is not fair and accountable community management, regardless of likings.

**Comment by vrurg** [comment]
Unfortunately, I don't see much for a discussion here. First of all, I concur to the statement that your statements are unconstructive. They add no value to the discussion.

Technically, one should've stopped talking and start thinking at the point where they find out about the birthdays of both projects, where MoarVM is born on 2012 and Rust is officially proclaimed stable on 2015.

But the primary reason why the ban is well-grounded comes down to "making personal remarks" point. Not only statements about "running off", "nepotism", and others were addressing personally Jonathan and labeling him with negative tags. But it's been done in his absence.

Not only it's been done once, but repeated again and again over the course of a few minutes.

Now, speaking of the accusations against Liz, I somewhat agree that she stepped over the line a little. She should've explained the ban before issuing it; I'm referring to the discord banning moment here as later the ban reason has been made all clear. Also, the remark about frustration was redundant. Yet, as I stated it already, the ban was well-grounded and necessary action in first place. Second, I totally agree to [the following](https://irclogs.raku.org/raku-dev/2024-01-10.html#16:55-0001):

> so please, stop this, and instead of complaining about what other people have or have not done
> do something productive 

At this point I live this issue open until the next RSC meeting. Until then I cannot guarantee any further official replies unless consider them absolutely necessary.

**Comment by vrurg** [comment]
Now, I take off the mantle, pick a glass of wine, settle back in my chair, and say one thing as my deeply personal opinion:

When anybody performs personal attacks on somebody else, for these attacks to be considered seriously the merits of the attacker must compare to the merits of the one their attack. Or, at cleat, they have to be at comparable level. Unfortunately, lengthy philosophical speeches, often based on incorrect premises (like the one above), add no value neither to the person making them, nor (and that's much worse) to the community the speeches are addressed to. Not to mention the dangerous and destructive controversy they bring in.

**Comment by 2colours** [comment]
I'm not sure if there is any merit to argue whether my remarks add to the discussion or not. I do think they add to the discussion because it makes a huge difference regarding the future of the project if influential people are willing to consider that relying solely on Jonathan Worthington's work - who has been really close to AWOL for years - has proved to be a mistake, and nobody should feel obliged to stick to any technical decision for Raku, whether it's in Rakudo, MoarVM or about any alternative technology that could replace them. (Yes, this was never about Rust and ages-old MoarVM decisions but rather how to relate to them in the "modern times".)

> But the primary reason why the ban is well-grounded comes down to "making personal remarks" point. Not only statements about "running off", "nepotism", and others were addressing personally Jonathan and labeling him with negative tags. But it's been done in his absence.

We seem to have fundamentally different understanding of what makes a "personal remark" (I wonder whether "personal remark" and "personal attack" are synonymous but let's not digress too much). I don't think it's "personal" to say that somebody practically abandoned a project that was completely built upon both his work and his role - these are all things that are not tied to somebody's personality or private life but public activity and contribution. The statement can be right or wrong but it's not an insult.
For "nepotism", more accurately I said that the way this project is run is closer to nepotism than to meritocracy, not that people are granted privileges literally based on familiarity and blood relations. I admit that out of the two mentioned things, this does have a somewhat accusing tone - but it seems to me the circumstances of my ban do kind of confirm the point of this criticism. There are people who stand up each other more because of personal liking than either some factual merit or a chosen value to stand by.

So I can't agree with the reasoning of the ban and I'm particularly annoyed about the apparent ignoring of these messages:
> don't import your political frustrations into Raku, please 
> that you live in a country that is very close to being totalitarian, does not mean that it is happening everywhere

Unlike my remarks, the implication that I'm only recognizing certain actions as totalitarian because I "live in a country that is very close to being totalitarian" (which I don't think is anyone's business to inform me about anyway) is really solely personal. Just that I don't keep it a secret where I live doesn't make it anyone's business and how "constructive" is it, really, to imply that I'm only stating something because of my completely unrelated life circumstances...

So it's not just an admin is allowed to act like that while I'm not, I'd say there even is a qualitative difference between the things we said.

**Comment by 2colours** [comment]
As for the merits... I take your point is that I shouldn't "attack" Jonathan Worthington's role and responsibility in the project because I haven't done remotely as much. I think if we can move on from the "attack" narrative and rather talk about "challenge" or "criticism", this reasoning falls apart.

Honestly, I would be the happiest if I didn't have to say these things - the problem is, nobody else does say them, so I don't know a better option... I gain exactly nothing by pointing out that this project have been governed into a dire situation, mostly by somebody who didn't even bother to share his personal knowledge so that somebody else can pick the work up, and that all this came at the expense of somebody (namely AlexDaniel) who might not have been a compiler wizard but always did a way greater job at managing anything he had been entrusted with. But these things don't go away just by not saying them. I could wait for all my life for _you all_ to draw conclusions from this but it's just not happening.

I think the merits _of the statements_ should be considered first and foremost.

Also, it honestly irks me a very bad way that Jonathan's merits have to be brought up over and over when he in fact got a chance that most people only dream of: he did something for fun and a lot of people cherished it, followed, helped out... as much as we are talking about tremendous work, we could say that his hobby project got gifted a community. And personally, apart from the project management implications, this is what bothers me the most: I think this once in a lifetime opportunity should be treated with much more respect and sense of responsibility. But that is indeed just my very personal opinion.

**Comment by finanalyst** [comment]
@2colours Hi Marton,
I have come to welcome your attention to detail and your contributions to the work I have done on the documentation website. I also consider it to be one of the brightest times of 2023 for me, when I was able to meet for the first time with Liz and for the second time since the 2000's with Jonathan this summer. 

So a conflict like this between people I admire is very painful to me personally. I hope that taking a little time to cool off, and to reconsider words said might lead to some reconciliation. 

Within your comments, both here and on the IRC which led to the ban, I can see some elements of ideas that could be reasonable concerns that I might agree to. But having lived 66 years now, and having observed the development of Raku from its inception, it does seem to me that what you actually wrote, and the way you expressed yourself, is likely to lead to the very opposite result to what you imply is your intention.

In all human endeavors, particularly those undertaken as a group, the most important and valuable asset is the quality of human interaction. You may consider this an opinion, but it is one I have come to based on conclusions about human society and civilisations since the beginning of recorded history. As with all valuable things, conserving good quality human interaction comes with a price. It is not always easy to be patient, or for us to understand another person's motivations and fragilities - we all have weak points - and none of us can see into the lives of others. Because human interaction is so valuable, community moderators SHOULD act quickly when it is imperiled. Their actions are not driven by the ideas embedded in destructive posts, or criticisms based on unpalatable truths, but by a desire to maintain an environment of respect and trust in which people can see their work and activity is valued by the community at large.

You mentioned one name - Jonathan - but during the time I have been observing the language, central figures in the development of Raku have been Larry, Audrey, Patrick and more recently Jonathan, and I am not able to mention many people like Liz, who has been at the heart of Raku, and was I believe one of the @Larry group. Raku has also seen a large number of people who have 'burnt out', people who have given a lot of time and effort, and then exhausted themselves. Often the final straw leading to their estrangement was being deeply offended by criticism of their work, often by critics who simply have not appreciated the toxicity of their words.

As to some of your conclusions about the way the Raku community is run, the evidence of my own experience does not support what you say. I am not a long-term friend, or a relative, of any of the other Council members. And I came into conflict with at least one other developer. But taken overall, I have found that Raku moderators and developers are inclusive, open to opposing opinions, quite quite brilliant intellectually, patient and appreciative of contributions to the Raku project.

**Comment by 2colours** [comment]
Dear Richard, I appreciate your considerate take.

I wouldn't question that moderation needs to be swift but I don't think "I didn't like what I just read" is actionable. I don't think it can lead to any sort of discussion if somebody is very much willing to put on a moderator hat and make one-sided decisions when they apparently have no problem making much more personally sensitive remarks. Other than meritocracy being seen as a somewhat outdated and not really inclusivity-friendly governance model, I would like to think there is nobody in the Raku community who thinks of meritocracy as "I'm doing it for power over the project".

I rather deleted a long "essay" about conflicts, the long story short would be that it really seems to me that the people who "survived" these conflicts are not only people who have been in good terms with each other but also typically the (only) people whose opinion of the Raku project didn't degrade over time. This is why it's so hard to communicate. The very people for whom MoarVM causes the most sweat and tears excuse the situation the most. I don't think this hostility to acknowledging mistakes should be taken so much for granted. There is no guarantee people who persisted were right in the "human interactions" and quite a lot of "human interactions" got decided by the state of the technology itself.

**Comment by vrurg** [comment]
I didn't want to touch that side of the discussion here, but applying term "nepotism" to the governance model of the community is totally incorrect anyway. First of all, my personal situation, when I started using Perl6 back then, was so that I barely knew anybody (conference for-a-minute crossovers don't count); and, more importantly, nobody knew me. Second, and more important point, is that the RSC is a result of open elections what makes the "nepotism" definition wrong in its depth.

> I rather deleted a long "essay" about conflicts, the long story short would be that it really seems to me that the people who "survived" these conflicts are not only people who have been in good terms with each other but also typically the (only) people whose opinion of the Raku project didn't degrade over time.

Just one thing to say here. Remember we had a meeting? Can you say you weren't given a chance? Another aspect of this: can you count the cases where you say nothing and out of the blue comes a Raku community member and presses an accusation against you? Don't raise the other hand, you wouldn't need it. Based on this I state that the quote above is not even an "unlucky guess" but another erroneous assertion. Moreover, some may consider it as offensive.

I don't see a reason to explain other mistakes and errors made. Marlon doesn't have a good habit of admitting his misconducts and mistakes, as I conclude from long term observations. Therefore it makes little sense to explain anything. 

This comment has the primary reason of having a clear display of why I consider accusations groundless and, as such, rather dangerous for the community.

**Comment by finanalyst** [comment]
@2colours Marton, I don't want to repeat anything, and so provide some grounds for you to respond. It seems to me that the best for all of us is for us all to take some time to think and re-evaluate. @vrurg Vadim hinted at a technique that is useful for people in a conflict - mentally and emotionally step away from the arguments, and look at what each person has said as if it were someone else. So, in this case, re-read your own words as if you were reading Joe Blogs (that's a made up name commonly used in England to mean some average person). 

As an aside, and to describe unintended consequences, I had allocated my time yesterday to describing how to write a new programming language in Welsh on the basis of Raku. It is remarkably easy, and absolutely sets Raku apart from all other significant languages. Instead of completing that task, I spent the time writing here. 

A final word about words. In Raku we make some very fine distinctions, such as between 'if' and 'with', one tests for truth and one for indefiniteness. Few of the other languages are so explicit about the difference. 

Since we understand how  important fine distinctions are, it should not be surprising for this community to be alert to the meanings of words we use in ordinary communications. So, 'nepotism' and 'despotic' have clear meanings, but they do not match the contexts in which you used them. Consequently, it seems that you have you have used them for their emotional content, rather than their semantic content. That is a common device in the world at large. None the less, if you use language with emotional force, then it should not be surprising for the response to be emotional as well. Consequently, it is not reasonable to say 'look at the statements', meaning look at the semantics of my communications, not the emotion. 

I'll end here as I have to go to a Welsh  lesson. 

Stay safe. Be kind. You were heard.

**Comment by 2colours** [comment]
@finanalyst I'm sorry to say but "despotic" absolutely does match the context in which I used it - it refers to unlimited and unaccounted abusive power. That's exactly what I meant and I stand by it. I don't think this should be swept under the rug. Please don't try to downplay it.

For "nepotism", I literally said "more like nepotism [than meritocracy]" as in closer to nepotism than to meritocracy. As long as we don't have a word for "allocating influence based on personal sympathy over merits", I don't think this is something to be called out. One may disagree with the sentiment but it's not term abuse, either.

**Comment by vrurg** [comment]
Despite my reluctance to react further I have to leave a couple of remarks here.

First of all, the person with moderating rights (a channel operator in the context) is by definition the one with "despotic" rights. But don't ignore the quotes because to be really despotic behavior has to be:

1. abusing the powers
2. using them in suppressive manner to personal opposition
3. performing it on a regular basis

The items are not applicable to the situation because, by sweeping back through the history of IRC logs, one can easily find a couple more cases where ban would be appropriate. All was tolerated instead.

Moreover, the IRC channel has not one but few operators. Nobody objected to the decision. Hence it can be considered as collegial. Voting doesn't always has to be explicit.

Then even more. We should keep in mind that nobody in the community objected to the ban. Correct me if I miss something, but so far it's nobody.

Next, the "nepotism" thing. Here, it comes to the point where I would demand a proof. After all, that's a technique many propaganda monsters are using elsewhere. Never expected to meet it in here. The technique is based upon a thrown in accusation when the burden of disproving it is offloaded to the one who is being accused.

This is not how things must work. Therefore I state here that the charges are false until proved, with facts, otherwise.

Going a little bit down to more personal view, it takes one to avoid reading any discussions people are having around various community and language related topics to say that personal sympathies play so much role here. I'm refusing to say that they are not out there because it is impossible to avoid them in real life. They never played any significant role in collective decisions made. Especially when it comes down to some very emotionally charged subjects.

**Comment by 2colours** [comment]
> The items are not applicable to the situation because, by sweeping back through the history of IRC logs, one can easily find a couple more cases where ban would be appropriate. All was tolerated instead.

I think this is a kind of statement that would require serious justification, not just taken at face value. Especially not after several occasions of putting words into my mouth - just take this occasion where you took my words as "why wasn't MoarVM written in Rust all along", something that I never said in any shape or form.

> Moreover, the IRC channel has not one but few operators. Nobody objected to the decision. Hence it can be considered as collegial. Voting doesn't always has to be explicit.

I don't think silencing somebody because somebody else doesn't want to hear what they say qualifies as any sort of voting. It much rather qualifies as "abusing the powers in a suppressive manner to personal opposition", and I opened this issue because that was all I could do in hope of any sort of justice. If people in charge are backing each other up, I'm not surprised - but there simply had to be some sort of visible evidence that _anybody_ could evaluate.

> Then even more. We should keep in mind that nobody in the community objected to the ban. Correct me if I miss something, but so far it's nobody.

I'm honestly not sure what you are trying to say with this. I think I could "mobilize" a couple of people against the ban - the ban that most people don't know or care about - but what difference does it make exactly? Are you implying what happened was alright just because nobody explicitly stood up for me? I thought justice in a highly international and supposedly inclusive environment was a bit more absolute or universal than this... I don't want to say analogies from history.

In general, we know that it's the default to just not do anything. Nobody lobbied for my ban either, and the operators who "voted" by not doing anything could always just argue that they didn't do anything, or that they didn't want to confront a comrade. It rather seems to me that all of this can fit very well into my narrative.

I don't think certain things can be decided by colliding narratives. I wouldn't be putting this issue up here hoping that somebody just buys into my narrative. There are things that shouldn't be a matter of opinion. What is "personal" and what isn't shouldn't be a matter of opinion. What is a proper course of action for moderation and what isn't also shouldn't be a matter of opinion.

**Comment by finanalyst** [comment]
@2colours Marton, my sincere and friendly advice was for us to take some time away, and to reconsider words as if they were said by someone else.
It would be possible for you to have the last word in this thread by saying something like: 'I will consider what you have said, but I do have concerns about the ongoing development of Raku as I have said before'. 
Instead, you are doubling down on your *opinions*. Vadim has suggested the IRC logs contain occasions of aggressive interactions, and they are a source of fact. Instead of looking widely, you focus on a single instance, where perhaps you were misunderstood. Your retort is - whether you are aware of the fact or not - a classical oratorical technique where the orator chooses a single instance in order to deflect from a general trend. 
The more you react, the more you are highlighting (to me at least) some of the logical weaknesses of your position. I did consider dissecting each of the oratorical devices you have used, but it would be too long. I do recommend you look at some articles about oratorical fallacies, topics such as 'strawman' and 'ad hominem'. 

The last thing you said was
> There are things that shouldn't be a matter of opinion. What is "personal" and what isn't shouldn't be a matter of opinion. What is a proper course of action for moderation and what isn't also shouldn't be a matter of opinion.

I entirely agree with you. There are things that should not be a matter of opinion. Some topics should not be decided by one person saying ***I think ...***. It is for that very reason that in a community such as the Raku community, we have several moderators, and there is a collective decision making process. It is best for a community for each of us as individuals to listen to the what other people have to say and to take account of the consensus. The consensus may be manifested by silence. I think that is what Vadim is trying to tell you.
 
But in case you conclude that I am trying to say a collective view is right and a dissenting individual is wrong, I am not!!!!! The individual can be right and the group wrong. I have personally been in a situation in which a group of my friends strongly disagreed with me. In the end, I was proved right, and the collective was not. But for the sake of harmony with my friends I acquiesced to their view. Time proved me right, but it was so much easier for us all to find a resolution because I had not made enemies of my friends. (FYI the opposite has more frequently happened, and I was proved wrong)

Patience is the key; valuing human interaction is important; observing silence and seeing what will happen is sometimes the sign of wisdom.

The moderator was not 'despotic' in stopping a conversation that was becoming toxic, and the Raku governance process is not afflicted by 'nepotism'. In this, I join with Vadim, not because we form some sort of elite, but because I agree with him, and I disagree with you. That does not prevent me from continuing to value your contributions.

Your passion is visible, your concern is understandable in some part, and please be assured you were heard.

**Comment by vrurg** [comment]
In order to prevent pointless circling around I'm locking this issue.

**Comment by lizmat** [comment]
Closing issue in light of RSC's decision: https://github.com/Raku/Raku-Steering-Council/blob/main/announcements/20240117.md
